### PR TITLE
Prearing new release 3.2.1

### PR DESCRIPTION
**Pull request by andriyun**
Changes partially have been released in https://github.com/OS2Forms/os2forms/tree/3.2.0

The real diff btw 3.2.0 and future 3.2.1 can be seen here https://github.com/OS2Forms/os2forms/compare/3.2.0...develop

### CODE REVIEW

**Comment by andriyun** [comment]
@stanbellcom Please review changes that has been added  on from Bellcom

@madsnorgaard Please view changes that has been added on behalf of ITK and Magenta

Thx

**Review by stanbellcom — COMMENTED** [review]
@andriyun i confirm the changes done by Bellcom are correct

**Comment by madsnorgaard** [comment]
@andriyun I too can confirm that we have all changes in this MR and that these are correct.

**Review by madsnorgaard — APPROVED** [review]

**Comment by andriyun** [comment]
Thx mates
I'd like to include one more change into 3.2.1 release.
See https://github.com/OS2Forms/os2forms/pull/25

**Pull request merged**
